"""initial schema

Revision ID: 333a3d9a45d5
Revises: 
Create Date: 2026-09-08 12:04:34.930449

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '333a3d9a45d5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_name'), 'awards', ['name'], unique=False)
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_goalie_coach', sa.Integer(), nullable=True),
    sa.Column('is_assistant', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_full_name'), 'coaches', ['full_name'], unique=False)
    op.create_index(op.f('ix_coaches_last_name'), 'coaches', ['last_name'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_imports_data_type'), 'data_imports', ['data_type'], unique=False)
    op.create_index(op.f('ix_data_imports_season_id'), 'data_imports', ['season_id'], unique=False)
    op.create_index(op.f('ix_data_imports_source_id'), 'data_imports', ['source_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('license_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('franchises',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=True),
    sa.Column('place_name', sa.String(length=100), nullable=True),
    sa.Column('raw_tricode', sa.String(length=10), nullable=True),
    sa.Column('tricode', sa.String(length=10), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('successor_franchise_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_managers_full_name'), 'general_managers', ['full_name'], unique=False)
    op.create_index(op.f('ix_general_managers_last_name'), 'general_managers', ['last_name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nhl_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('position_code', sa.String(length=5), nullable=True),
    sa.Column('primary_position', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('birth_city', sa.String(length=100), nullable=True),
    sa.Column('birth_country', sa.String(length=100), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('shoots_catches', sa.String(length=1), nullable=True),
    sa.Column('is_goalie', sa.Integer(), nullable=True),
    sa.Column('is_rookie', sa.Integer(), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('draft_round', sa.Integer(), nullable=True),
    sa.Column('draft_overall', sa.Integer(), nullable=True),
    sa.Column('draft_team', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_first_name'), 'players', ['first_name'], unique=False)
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_last_name'), 'players', ['last_name'], unique=False)
    op.create_index(op.f('ix_players_position_code'), 'players', ['position_code'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formatted_id', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('regular_season_end_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('regular_season_games', sa.Integer(), nullable=True),
    sa.Column('total_regular_season_games', sa.Integer(), nullable=True),
    sa.Column('total_playoff_games', sa.Integer(), nullable=True),
    sa.Column('number_of_teams', sa.Integer(), nullable=True),
    sa.Column('season_ordinal', sa.Integer(), nullable=True),
    sa.Column('ties_used', sa.Integer(), nullable=True),
    sa.Column('ot_loss_point', sa.Integer(), nullable=True),
    sa.Column('wildcard_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goalie_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_abbrevs', sa.String(length=50), nullable=True),
    sa.Column('game_type', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('shots_against', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('save_pct', sa.Float(), nullable=True),
    sa.Column('goals_against_average', sa.Float(), nullable=True),
    sa.Column('shutouts', sa.Integer(), nullable=True),
    sa.Column('time_on_ice', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('penalty_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goalie_season_stats_player_id'), 'goalie_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_goalie_season_stats_season_id'), 'goalie_season_stats', ['season_id'], unique=False)
    op.create_table('player_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('seasons', sa.String(length=50), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_positions_player_id'), 'player_positions', ['player_id'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_abbrevs', sa.String(length=50), nullable=True),
    sa.Column('game_type', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('penalty_minutes', sa.Integer(), nullable=True),
    sa.Column('ev_goals', sa.Integer(), nullable=True),
    sa.Column('ev_points', sa.Integer(), nullable=True),
    sa.Column('pp_goals', sa.Integer(), nullable=True),
    sa.Column('pp_points', sa.Integer(), nullable=True),
    sa.Column('sh_goals', sa.Integer(), nullable=True),
    sa.Column('sh_points', sa.Integer(), nullable=True),
    sa.Column('game_winning_goals', sa.Integer(), nullable=True),
    sa.Column('ot_goals', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shooting_pct', sa.Float(), nullable=True),
    sa.Column('faceoff_win_pct', sa.Float(), nullable=True),
    sa.Column('time_on_ice_per_game', sa.Float(), nullable=True),
    sa.Column('shifts_per_game', sa.Float(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('blocked_shots', sa.Integer(), nullable=True),
    sa.Column('takeaways', sa.Integer(), nullable=True),
    sa.Column('giveaways', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('shots_against', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('save_pct', sa.Float(), nullable=True),
    sa.Column('goals_against_average', sa.Float(), nullable=True),
    sa.Column('shutouts', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('time_on_ice', sa.Integer(), nullable=True),
    sa.Column('is_goalie', sa.Integer(), nullable=True),
    sa.Column('goalie_stats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_season_stats_player_id'), 'player_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_season_id'), 'player_season_stats', ['season_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nhl_id', sa.Integer(), nullable=True),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('tricode', sa.String(length=10), nullable=True),
    sa.Column('first_season_id', sa.Integer(), nullable=True),
    sa.Column('last_season_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_first_season_id'), 'teams', ['first_season_id'], unique=False)
    op.create_index(op.f('ix_teams_franchise_id'), 'teams', ['franchise_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_season_id', sa.Integer(), nullable=True),
    sa.Column('end_season_id', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('avg_annual_value', sa.Float(), nullable=True),
    sa.Column('signing_bonus', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_player_id'), 'contracts', ['player_id'], unique=False)
    op.create_index(op.f('ix_contracts_team_id'), 'contracts', ['team_id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('minor_league_team', sa.String(length=200), nullable=True),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('nhlnail_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_pick_number'), 'draft_picks', ['pick_number'], unique=False)
    op.create_index(op.f('ix_draft_picks_player_id'), 'draft_picks', ['player_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_season_id'), 'draft_picks', ['season_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_team_id'), 'draft_picks', ['team_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_code', sa.String(length=10), nullable=True),
    sa.Column('away_team_code', sa.String(length=10), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('ot_sol', sa.String(length=10), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_season_id'), 'games', ['season_id'], unique=False)
    op.create_table('player_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_finalist', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('vote_pct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_awards_award_id'), 'player_awards', ['award_id'], unique=False)
    op.create_index(op.f('ix_player_awards_player_id'), 'player_awards', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_awards_season_id'), 'player_awards', ['season_id'], unique=False)
    op.create_table('player_team_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_team_seasons_player_id'), 'player_team_seasons', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_team_seasons_season_id'), 'player_team_seasons', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_team_seasons_team_id'), 'player_team_seasons', ['team_id'], unique=False)
    op.create_table('team_coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('playoff_games', sa.Integer(), nullable=True),
    sa.Column('playoff_wins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_coaches_coach_id'), 'team_coaches', ['coach_id'], unique=False)
    op.create_index(op.f('ix_team_coaches_season_id'), 'team_coaches', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_coaches_team_id'), 'team_coaches', ['team_id'], unique=False)
    op.create_table('team_gms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gm_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['gm_id'], ['general_managers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_gms_gm_id'), 'team_gms', ['gm_id'], unique=False)
    op.create_index(op.f('ix_team_gms_team_id'), 'team_gms', ['team_id'], unique=False)
    op.create_table('team_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('abbr', sa.String(length=10), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_identities_franchise_id'), 'team_identities', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_team_identities_team_id'), 'team_identities', ['team_id'], unique=False)
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('power_play_pct', sa.Float(), nullable=True),
    sa.Column('penalty_kill_pct', sa.Float(), nullable=True),
    sa.Column('power_play_goals', sa.Integer(), nullable=True),
    sa.Column('power_play_opportunities', sa.Integer(), nullable=True),
    sa.Column('shorthanded_goals', sa.Integer(), nullable=True),
    sa.Column('shorthanded_against', sa.Integer(), nullable=True),
    sa.Column('shots_per_game', sa.Float(), nullable=True),
    sa.Column('shots_against_per_game', sa.Float(), nullable=True),
    sa.Column('faceoff_pct', sa.Float(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('blocked_shots', sa.Integer(), nullable=True),
    sa.Column('takeaways', sa.Integer(), nullable=True),
    sa.Column('giveaways', sa.Integer(), nullable=True),
    sa.Column('penalty_minutes', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_season_stats_season_id'), 'team_season_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_season_stats_team_id'), 'team_season_stats', ['team_id'], unique=False)
    op.create_table('team_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('conference_rank', sa.Integer(), nullable=True),
    sa.Column('division_rank', sa.Integer(), nullable=True),
    sa.Column('playoffs_reached', sa.Integer(), nullable=True),
    sa.Column('stanley_cup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_seasons_season_id'), 'team_seasons', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_seasons_team_id'), 'team_seasons', ['team_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_player_id'), 'transactions', ['player_id'], unique=False)
    op.create_index(op.f('ix_transactions_season_id'), 'transactions', ['season_id'], unique=False)
    op.create_index(op.f('ix_transactions_team_id'), 'transactions', ['team_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('period_time', sa.String(length=10), nullable=True),
    sa.Column('strength', sa.String(length=20), nullable=True),
    sa.Column('strength_code', sa.String(length=5), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('assist_1_id', sa.Integer(), nullable=True),
    sa.Column('assist_2_id', sa.Integer(), nullable=True),
    sa.Column('secondary_ids', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assist_1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['assist_2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_event_type'), 'game_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_events_player_id'), 'game_events', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_events_player_id'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_event_type'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_team_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_season_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_player_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_team_seasons_team_id'), table_name='team_seasons')
    op.drop_index(op.f('ix_team_seasons_season_id'), table_name='team_seasons')
    op.drop_table('team_seasons')
    op.drop_index(op.f('ix_team_season_stats_team_id'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_season_id'), table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index(op.f('ix_team_identities_team_id'), table_name='team_identities')
    op.drop_index(op.f('ix_team_identities_franchise_id'), table_name='team_identities')
    op.drop_table('team_identities')
    op.drop_index(op.f('ix_team_gms_team_id'), table_name='team_gms')
    op.drop_index(op.f('ix_team_gms_gm_id'), table_name='team_gms')
    op.drop_table('team_gms')
    op.drop_index(op.f('ix_team_coaches_team_id'), table_name='team_coaches')
    op.drop_index(op.f('ix_team_coaches_season_id'), table_name='team_coaches')
    op.drop_index(op.f('ix_team_coaches_coach_id'), table_name='team_coaches')
    op.drop_table('team_coaches')
    op.drop_index(op.f('ix_player_team_seasons_team_id'), table_name='player_team_seasons')
    op.drop_index(op.f('ix_player_team_seasons_season_id'), table_name='player_team_seasons')
    op.drop_index(op.f('ix_player_team_seasons_player_id'), table_name='player_team_seasons')
    op.drop_table('player_team_seasons')
    op.drop_index(op.f('ix_player_awards_season_id'), table_name='player_awards')
    op.drop_index(op.f('ix_player_awards_player_id'), table_name='player_awards')
    op.drop_index(op.f('ix_player_awards_award_id'), table_name='player_awards')
    op.drop_table('player_awards')
    op.drop_index(op.f('ix_games_season_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_draft_picks_team_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_season_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_player_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_pick_number'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_contracts_team_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_player_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_teams_franchise_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_first_season_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_player_season_stats_season_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_player_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_player_positions_player_id'), table_name='player_positions')
    op.drop_table('player_positions')
    op.drop_index(op.f('ix_goalie_season_stats_season_id'), table_name='goalie_season_stats')
    op.drop_index(op.f('ix_goalie_season_stats_player_id'), table_name='goalie_season_stats')
    op.drop_table('goalie_season_stats')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_position_code'), table_name='players')
    op.drop_index(op.f('ix_players_last_name'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_first_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_general_managers_last_name'), table_name='general_managers')
    op.drop_index(op.f('ix_general_managers_full_name'), table_name='general_managers')
    op.drop_table('general_managers')
    op.drop_table('franchises')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_data_imports_source_id'), table_name='data_imports')
    op.drop_index(op.f('ix_data_imports_season_id'), table_name='data_imports')
    op.drop_index(op.f('ix_data_imports_data_type'), table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_index(op.f('ix_coaches_last_name'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_full_name'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_awards_name'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
